[package]
name = "tilejson"
version = "0.1.0"
description = "Library for serializing the TileJSON file format"
authors = ["Stepan Kuzmin <to.stepan.kuzmin@gmail.com>"]
license = "MIT"
license-file = "LICENSE"
documentation = "https://docs.rs/tilejson"
homepage = "https://github.com/stepankuzmin/rust-tilejson"
repository = "https://github.com/stepankuzmin/rust-tilejson"
readme = "README.md"
keywords = ["mapbox", "tilejson", "serde"]

[badges]
travis-ci = { repository = "stepankuzmin/rust-tilejson" }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"